### ISSUE TITLE
Update repo URL for pipes-rs

### ISSUE THREAD

**Issue by lhvy** [patevs/dotfiles#5]
Hi there! I just changed my GitHub username. In case someone makes an account with my old username and redirects stop working, I'd recommend changing the URL of pipes-rs in [tools.md](https://github.com/patevs/dotfiles/blob/master/docs/tools.md).

**Comment by patevs** [comment]
Fixed in [`v0.85.1`](https://github.com/patevs/dotfiles/releases/tag/v0.85.1).

Great work on a cool project!
